status = [
  "ubuntu_lint",
  "install (2.3.8)",
  "install (2.4.9)",
  "install (2.5.7)",
  "install (2.6.5)",
  "install (jruby-9.2.9.0)",
  "macos (2.4.9)",
  "ubuntu (2.4.9, rubygems)",
  "ubuntu (2.4.9, bundler)",
  "windows (2.4.9)",
  "macos (2.5.7)",
  "ubuntu (2.5.7, rubygems)",
  "ubuntu (2.5.7, bundler)",
  "windows (2.5.7)",
  "macos (2.6.5)",
  "ubuntu (2.6.5, rubygems)",
  "ubuntu (2.6.5, bundler)",
  "windows (2.6.5)",
  "ubuntu_bundler_master (2.6.5)",
  "ruby_master",
  "ubuntu (2.3.8, rubygems)",
  "unstable (ruby-head)",
  "ubuntu (jruby-9.2.9.0, rubygems)",
]

timeout_sec = 3600
prerun_timeout_sec = 3600
delete_merged_branches = true

[committer]
name = "Bundlerbot"
email = "bot@bundler.io"
