status = [
  "continuous-integration/travis-ci/push",
  "ubuntu_lint",
  "macos (2.3.x)",
  "ubuntu (2.3.x, rubygems)",
  "ubuntu (2.3.x, bundler)",
  "macos (2.4.x)",
  "ubuntu (2.4.x, rubygems)",
  "ubuntu (2.4.x, bundler)",
  "windows (2.4.x)",
  "macos (2.5.x)",
  "ubuntu (2.5.x, rubygems)",
  "ubuntu (2.5.x, bundler)",
  "windows (2.5.x)",
  "macos (2.6.x)",
  "ubuntu (2.6.x, rubygems)",
  "ubuntu (2.6.x, bundler)",
  "windows (2.6.x)",
  "ubuntu_bundler_master (2.6.x)",
  "ubuntu_rvm (ruby-head, rubygems)",
  "ubuntu_rvm (ruby-head, bundler)",
  "ubuntu_rvm (jruby-9.2.8.0, rubygems)",
]

timeout-sec = 14400
delete_merged_branches = true

[committer]
name = "Bundlerbot"
email = "bot@bundler.io"
