version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      artifacts:
        patterns:
          - "*-artifact"
  - package-ecosystem: 'cargo'
    directory: '/test/rubygems/test_gem_ext_cargo_builder/custom_name/ext/custom_name_lib'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'cargo'
    directory: '/test/rubygems/test_gem_ext_cargo_builder/rust_ruby_example/'
    schedule:
      interval: 'weekly'
