---
after_script:
- util/ci after_script
before_script:
- util/ci before_script
language: ruby
dist: trusty
sudo: required
branches:
  only:
    - master
    - auto
    - /^[\d.]+$/
    - /.+-stable$/
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.10
- 2.2.7
- 2.3.4
- 2.4.1
- ruby-head
env:
  - "TEST_TOOL=rubygems YAML=syck"
  - "TEST_TOOL=rubygems YAML=psych"
  - "TEST_TOOL=bundler RGV=master"
script:
- util/ci script
matrix:
  exclude:
    - rvm: 1.8.7
      env: "TEST_TOOL=rubygems YAML=psych"
    - rvm: 1.9.2
      env: "TEST_TOOL=bundler RGV=master"
    - rvm: 2.0.0
      env: "TEST_TOOL=rubygems YAML=syck"
    - rvm: 2.1.10
      env: "TEST_TOOL=rubygems YAML=syck"
    - rvm: 2.2.7
      env: "TEST_TOOL=rubygems YAML=syck"
    - rvm: 2.3.4
      env: "TEST_TOOL=rubygems YAML=syck"
    - rvm: 2.4.1
      env: "TEST_TOOL=rubygems YAML=syck"
    - rvm: ruby-head
      env: "TEST_TOOL=rubygems YAML=syck"
  allow_failures:
    - rvm: ruby-head
