---
after_script:
- rake travis:after -t
before_script:
- gem install hoe-travis --no-rdoc --no-ri
- rake travis:before -t
language: ruby
notifications:
  email:
  - drbrain@segment7.net
  - evan+notify@phx.io
  - kou@cozmixng.org
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- ruby-head
env:
  - "YAML=syck"
  - "YAML=psych"
script: rake travis
matrix:
  exclude:
    - rvm: ruby-head
      env: "YAML=syck"
  allow_failures:
    - rvm: 1.8.7
