language: ruby
dist: xenial
branches:
  only:
    - master
    - staging
    - trying
    - /^[\d.]+$/
    - /.+-stable$/
env:
  - "TEST_TOOL=rubygems"
  - "TEST_TOOL=bundler RGV=master"
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head
jobs:
  include:
    - stage: linting
      rvm: 2.6
      env:
        - "TEST_TOOL=rubygems"
      script: util/ci rubocop
stages:
  - linting
  - test
before_script:
  - util/ci before_script
script:
  - util/ci script
matrix:
  allow_failures:
    - rvm: ruby-head
      env: "TEST_TOOL=rubygems"
    - rvm: ruby-head
      env: "TEST_TOOL=bundler RGV=master"
