name: changelog-bundler

on:
  push:
    branches:
      - master

jobs:
  changelog_bundler:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
          bundler: none

      - name: Install dependencies
        run: bin/rake dev:deps
        working-directory: ./bundler

      - name: Sync changelog
        run: bin/rake release:sync_changelog[${{ github.events.after }}]
        working-directory: ./bundler

      - name: Set up git config
        run: |
          git config user.name "The Bundler Bot"
          git config user.email "bot@bundler.io"

      - name: Commit and push changes
        run: |
          if [ "$(git diff)" != "" ]
          then
            git add bundler/CHANGELOG.md
            git commit -m "Automatic changelog update"
            git push origin master
          fi
