name: daily-bundler

on:
  pull_request:

jobs:
  daily_bundler:
    name: Bundler (ruby-head)
    runs-on: ubuntu-20.04
    if: github.repository == 'rubygems/rubygems'
    env:
      RGV: ..
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-head
          bundler: none

      - name: Show Ruby version
        run: ruby --version

      - name: Prepare dependencies
        run: |
          sudo apt-get install graphviz -y
          rake spec:parallel_deps
        working-directory: ./bundler

      - name: Run Test
        run: |
          bin/rake spec:all
        working-directory: ./bundler

      - name: Get previous status
        if: always()
        run: echo "OLD_STATUS=$(curl -sS 'https://api.github.com/repos/rubygems/rubygems/actions/workflows/daily-bundler.yml/runs?event=schedule&branch=master' | jq '.workflow_runs | .[1].conclusion')" >> $GITHUB_ENV

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() && env.OLD_STATUS == '"success"'

    timeout-minutes: 60
