name: daily-bundler

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

defaults:
  run:
    shell: bash
    working-directory: ./bundler

jobs:
  daily_bundler:
    name: Bundler (ruby-head)
    runs-on: ubuntu-22.04
    if: github.repository == 'rubygems/rubygems'
    env:
      RGV: ..
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@93287a1fa82c6ddbb6d8db978df4b0119cd8879f # v1.133.2
        with:
          ruby-version: ruby-head
          bundler: none

      - name: Show Ruby version
        run: ruby --version

      - name: Prepare dependencies
        run: |
          sudo apt-get install graphviz -y
          bin/rake spec:parallel_deps

      - name: Run Test
        run: |
          bin/rake spec:all

      - name: Get previous status
        if: always()
        run: echo "OLD_STATUS=$(curl -sS 'https://api.github.com/repos/rubygems/rubygems/actions/workflows/daily-bundler.yml/runs?event=schedule&branch=master' | jq '.workflow_runs | .[1].conclusion')" >> $GITHUB_ENV

      - uses: 8398a7/action-slack@bdc6f9de222d3b7518e6cf99c4f3410f653cfde3 # v3.15.0
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() && env.OLD_STATUS == '"success"'

    timeout-minutes: 60
