name: daily-rubygems

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  daily_rubygems:
    name: Rubygems (ruby-head)
    runs-on: ubuntu-20.04
    if: github.repository == 'rubygems/rubygems'
    strategy:
      fail-fast: false
      matrix:
        ruby: [ ruby-head, truffleruby-head ]
    env:
      TRUFFLERUBYOPT: "--experimental-options --testing-rubygems"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Show Ruby version
        run: ruby --version

      - name: Test rubygems
        run: |
          rake setup
          rake test

      - name: Get previous status
        if: always()
        run: echo "OLD_STATUS=$(curl -sS 'https://api.github.com/repos/rubygems/rubygems/actions/workflows/daily-rubygems.yml/runs?event=schedule&branch=master' | jq '.workflow_runs | .[1].conclusion')" >> $GITHUB_ENV

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,action,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() && env.OLD_STATUS == '"success"'

    timeout-minutes: 60
