name: daily-rubygems

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  daily_rubygems:
    name: Rubygems (${{ matrix.ruby }})
    runs-on: ${{ matrix.os }}
    if: github.repository == 'rubygems/rubygems'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        ruby: [ ruby-head, truffleruby-head ]
        cargo: [ stable ]
        include:
          - { os: windows-2022, ruby: mswin, cargo: stable-x86_64-pc-windows-gnu }
    env:
      TRUFFLERUBYOPT: "--experimental-options --testing-rubygems"
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@319066216501fbd5e2d568f14b7d68c19fb67a5d # v1.133.1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - uses: dtolnay/rust-toolchain@e645b0cf01249a964ec099494d38d2da0f0b349f
        with:
          toolchain: ${{ matrix.cargo }}
          components: rustfmt

      - name: Show Ruby version
        run: ruby --version

      - name: Test rubygems
        run: |
          rake setup
          rake test

      - name: Get previous status
        if: always()
        run: echo "OLD_STATUS=$(curl -sS 'https://api.github.com/repos/rubygems/rubygems/actions/workflows/daily-rubygems.yml/runs?event=schedule&branch=master' | jq '.workflow_runs | .[1].conclusion')" >> $GITHUB_ENV

      - uses: 8398a7/action-slack@bdc6f9de222d3b7518e6cf99c4f3410f653cfde3 # v3.15.0
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,action,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() && env.OLD_STATUS == '"success"'

    timeout-minutes: 60
