name: daily-rubygems

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  daily_rubygems:
    name: Rubygems (${{ matrix.ruby }})
    runs-on: ${{ matrix.os }}
    if: github.repository == 'rubygems/rubygems'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        ruby: [ ruby-head, truffleruby-head ]
        cargo: [ stable ]
        include:
          - { os: windows-2022, ruby: mswin, cargo: stable-x86_64-pc-windows-gnu }
    env:
      TRUFFLERUBYOPT: "--experimental-options --testing-rubygems"
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@c7079efafd956afb5d823e8999c2506e1053aefa # v1.126.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: ${{ matrix.cargo }}

      - name: Show Ruby version
        run: ruby --version

      - name: Test rubygems
        run: |
          rake setup
          rake test

      - name: Get previous status
        if: always()
        run: echo "OLD_STATUS=$(curl -sS 'https://api.github.com/repos/rubygems/rubygems/actions/workflows/daily-rubygems.yml/runs?event=schedule&branch=master' | jq '.workflow_runs | .[1].conclusion')" >> $GITHUB_ENV

      - uses: 8398a7/action-slack@a189acbf0b7ea434558662ae25a0de71df69a435 # v3.14.0
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,action,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() && env.OLD_STATUS == '"success"'

    timeout-minutes: 60
