name: macos_rubygems

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2

jobs:
  macos_rubygems:
    name: Rubygems on MacOS (${{ matrix.ruby.name }})
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: "2.4", value: 2.4.10 }
          - { name: "2.5", value: 2.5.9 }
          - { name: "2.6", value: 2.6.7 }
          - { name: "2.7", value: 2.7.3 }
          - { name: "3.0", value: 3.0.1 }
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Test
        run: rake test
    timeout-minutes: 15
