name: macos-rubygems

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  macos_rubygems:
    name: Rubygems on MacOS (${{ matrix.ruby.name }})
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: "2.6", value: 2.6.10 }
          - { name: "2.7", value: 2.7.7 }
          - { name: "3.0", value: 3.0.5 }
          - { name: "3.1", value: 3.1.3 }
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Setup ruby
        uses: ruby/setup-ruby@03b78bdda287ae04217ee12e4b64996630a03542 # v1.131.0
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Test
        run: rake test
    timeout-minutes: 20
