name: main-bundler

on:
  pull_request:

  push:
    branches:
      - master
      - macos_ci
      - 3.2

jobs:
  main_bundler:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.3.8, 2.4.10, 2.5.8, 2.6.6, 2.7.2 ]
        bundler: [ '', 3.0.0 ]
        os: [ ubuntu-18.04 ]
        exclude:
          - { bundler: 3.0.0, ruby: 2.3.8 }
        include:
          - { bundler: '', ruby: 2.7.2, os: macos-10.15 }
    env:
      RGV: ..
      RUBYOPT: --disable-gems
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Install graphviz
        run: sudo apt-get install graphviz -y
        if: matrix.bundler == ''
      - name: Replace version
        run: BUNDLER_SPEC_SUB_VERSION=${{ matrix.bundler }} bin/rake override_version
        if: matrix.bundler != ''
        working-directory: ./bundler
      - name: Prepare dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
      - name: Run Test
        run: |
          bin/rake spec:all
        working-directory: ./bundler
    timeout-minutes: 60
