name: older-rubygems-bundler

on:
  pull_request:
    paths:
      - bundler/**
      - .github/workflows/older-rubygems-bundler.yml
      - .rubocop_bundler.yml

  push:
    branches:
      - master
      - 3.3

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  older_rubygems_bundler:
    name: Bundler ${{ matrix.bundler.name }} against old Rubygems (${{ matrix.ruby.name }}, ${{ matrix.rgv.name }})
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.3, value: 2.3.8 }, rgv: { name: rgv-2.5, value: v2.5.2 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.4, value: 2.4.10 }, rgv: { name: rgv-2.6, value: v2.6.14 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.5, value: 2.5.9 }, rgv: { name: rgv-2.7, value: v2.7.11 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.6, value: 2.6.9 }, rgv: { name: rgv-3.0, value: v3.0.9 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.7, value: 2.7.5 }, rgv: { name: rgv-3.1, value: v3.1.5 } } # Not using 3.1.6 because it's not tagged on GitHub for some reason
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-3.0, value: 3.0.3 }, rgv: { name: rgv-3.2, value: v3.2.33 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-3.1, value: 3.1.1 }, rgv: { name: rgv-3.3, value: v3.3.5 } }
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-2.7, value: 2.7.5 }, rgv: { name: rgv-3.1, value: v3.1.5 } } # Not using 3.1.6 because it's not tagged on GitHub for some reason
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-3.0, value: 3.0.3 }, rgv: { name: rgv-3.2, value: v3.2.33 } }
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-3.1, value: 3.1.1 }, rgv: { name: rgv-3.3, value: v3.3.5 } }
    env:
      RGV: ${{ matrix.rgv.value }}
      RUBYOPT: --disable-gems
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: bundler/tmp/rubygems
          ref: ${{ matrix.rgv.value }}
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install graphviz
        run: sudo apt-get install graphviz -y
        if: matrix.bundler.value == ''
      - name: Replace version
        run: BUNDLER_SPEC_SUB_VERSION=${{ matrix.bundler.value }} bin/rake override_version
        if: matrix.bundler.value != ''
        working-directory: ./bundler
      - name: Prepare dependencies
        run: |
          rake spec:parallel_deps
        working-directory: ./bundler
      - name: Run Test
        run: |
          bin/rake spec:all
        working-directory: ./bundler
      - name: Run Rubygems Requirement tests against local bundler, to make sure bundler monkeypatches preserve the behaviour
        run: |
          ruby -I../../lib:lib:test test/rubygems/test_gem_requirement.rb
        working-directory: ./bundler/tmp/rubygems
    timeout-minutes: 60
