name: older-rubygems-bundler

on:
  pull_request:
    paths:
      - bundler/**
      - .github/workflows/older-rubygems-bundler.yml
      - .rubocop_bundler.yml

  push:
    branches:
      - master
      - 3.2

jobs:
  older_rubygems_bundler:
    name: Bundler ${{ matrix.bundler.name }} against old Rubygems (${{ matrix.ruby.name }}, ${{ matrix.rgv.name}})
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: ruby-2.3, value: 2.3.8 }
          - { name: ruby-2.4, value: 2.4.10 }
          - { name: ruby-2.5, value: 2.5.8 }
          - { name: ruby-2.6, value: 2.6.6 }
          - { name: ruby-2.7, value: 2.7.2 }
        rgv:
          - { name: rgv-2.5, value: v2.5.2 }
          - { name: rgv-2.6, value: v2.6.14 }
          - { name: rgv-2.7, value: v2.7.10 }
          - { name: rgv-3.0, value: v3.0.8 }
          - { name: rgv-3.1, value: v3.1.4 }

        bundler:
          - { name: 2, value: '' }

        exclude:
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.4, value: 2.4.10 }, rgv: { name: rgv-2.5, value: v2.5.2 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.5, value: 2.5.8 }, rgv: { name: rgv-2.5, value: v2.5.2 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.5, value: 2.5.8 }, rgv: { name: rgv-2.6, value: v2.6.14 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.6, value: 2.6.6 }, rgv: { name: rgv-2.5, value: v2.5.2 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.6, value: 2.6.6 }, rgv: { name: rgv-2.6, value: v2.6.14 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.6, value: 2.6.6 }, rgv: { name: rgv-2.7, value: v2.7.10 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.7, value: 2.7.2 }, rgv: { name: rgv-2.5, value: v2.5.2 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.7, value: 2.7.2 }, rgv: { name: rgv-2.6, value: v2.6.14 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.7, value: 2.7.2 }, rgv: { name: rgv-2.7, value: v2.7.10 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.7, value: 2.7.2 }, rgv: { name: rgv-3.0, value: v3.0.8 } }

        include:
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-2.4, value: 2.4.10 }, rgv: { name: rgv-3.1, value: v3.1.4 } }
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-2.5, value: 2.5.8 }, rgv: { name: rgv-3.1, value: v3.1.4 } }
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-2.6, value: 2.6.6 }, rgv: { name: rgv-3.1, value: v3.1.4 } }
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-2.7, value: 2.7.2 }, rgv: { name: rgv-3.1, value: v3.1.4 } }
    env:
      RGV: ${{ matrix.rgv.value }}
      RUBYOPT: --disable-gems
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install graphviz
        run: sudo apt-get install graphviz -y
        if: matrix.bundler.value == ''
      - name: Replace version
        run: BUNDLER_SPEC_SUB_VERSION=${{ matrix.bundler.value }} bin/rake override_version
        if: matrix.bundler.value != ''
        working-directory: ./bundler
      - name: Prepare dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
      - name: Run Test
        run: |
          bin/rake spec:all
        working-directory: ./bundler
    timeout-minutes: 60
