name: ruby-core

on:
  pull_request:
  merge_group:

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ruby_core:
    name: ${{matrix.target}} under a ruby-core setup
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target: [Rubygems, Bundler]
    steps:
      - name: Set up latest ruby head
        uses: ruby/setup-ruby@9669f3ee51dc3f4eda8447ab696b3ab19a90d14b # v1.144.0
        with:
          ruby-version: head
          bundler: none
      - name: Save latest buildable revision to environment
        run: echo "REF=$(ruby -v | cut -d')' -f1 | cut -d' ' -f5)" >> $GITHUB_ENV
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          repository: ruby/ruby
          path: ruby/ruby
          fetch-depth: 10
      - name: Checkout the latest buildable revision
        run: git switch -c ${{ env.REF }}
        working-directory: ruby/ruby
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update -q || :
          sudo apt-get install --no-install-recommends -q -y build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm-dev bison autoconf ruby
      - name: Build Ruby
        run: |
          ./autogen.sh
          ./configure -C --disable-install-doc
          make -j2
        working-directory: ruby/ruby
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          path: rubygems/rubygems
      - name: Sync tools
        run: |
          ruby tool/sync_default_gems.rb rubygems
        working-directory: ruby/ruby
      - name: Test RubyGems
        run: make -j2 -s test-all TESTS="rubygems --no-retry"
        working-directory: ruby/ruby
        if: matrix.target == 'Rubygems'
      - name: Test Bundler
        run: |
          git add .
          make test-bundler-parallel
        working-directory: ruby/ruby
        if: matrix.target == 'Bundler'
