name: rubygems

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  rubygems:
    name: Rubygems on ${{ matrix.os.name }} (${{ matrix.ruby.name }})
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: Ubuntu, value: ubuntu-22.04 }
          - { name: macOS, value: macos-13 }
          - { name: Windows, value: windows-2022 }

        ruby:
          - { name: "3.0", value: 3.0.6 }
          - { name: "3.1", value: 3.1.4 }
          - { name: "3.2", value: 3.2.3 }
          - { name: "3.3", value: 3.3.0 }

        include:
          - ruby: { name: jruby-9.4, value: jruby-9.4.2.0 }
            os: { name: Ubuntu, value: ubuntu-22.04 }

          - ruby: { name: truffleruby-23, value: truffleruby-23.1.1 }
            os: { name: Ubuntu, value: ubuntu-22.04 }

          - os: { name: Windows, value: windows-2022 }
            ruby: { name: mswin, value: mswin }

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup ruby (Ubuntu/macOS)
        uses: ruby/setup-ruby@bd03e04863f52d169e18a2b190e8fa6b84938215 # v1.170.0
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
        if: matrix.os.name != 'Windows'
      - name: Setup ruby (Windows)
        uses: ruby/setup-ruby-pkgs@c7f324bc4a9434f2ce3e55fa1cc19e41daecb231 # v1.33.1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
          mingw: clang
        if: matrix.os.name == 'Windows'
      - name: Configure bindgen
        shell: pwsh
        run: |
          echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
          echo "BINDGEN_EXTRA_CLANG_ARGS=$((gcm clang).source -replace "bin\clang.exe","include")" >> $env:GITHUB_ENV
        if: matrix.ruby.name == 'mswin'
      - name: Install Dependencies
        run: rake setup
      - name: Run Test
        run: rake test
        if: "!startsWith(matrix.ruby.name, 'truffleruby') && !startsWith(matrix.ruby.name, 'jruby')"
      - name: Run Test isolatedly
        run: rake test:isolated
        if: matrix.ruby.name == '3.3' && matrix.os.name != 'Windows'
      - name: Run Test (JRuby)
        run: JRUBY_OPTS=--debug rake test
        if: startsWith(matrix.ruby.name, 'jruby')
      - name: Run Test (Truffleruby)
        run: TRUFFLERUBYOPT="--experimental-options --testing-rubygems" rake test
        if: startsWith(matrix.ruby.name, 'truffleruby')

    timeout-minutes: 60
