name: ubuntu-rubygems

on:
  pull_request:

  push:
    branches:
      - master
      - 3.4

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ubuntu_rubygems:
    name: Rubygems on ${{ matrix.os.name }} (${{ matrix.ruby.name }})
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: Ubuntu, value: ubuntu-22.04 }
          - { name: MacOS, value: macos-12 }

        ruby:
          - { name: "2.6", value: 2.6.10 }
          - { name: "2.7", value: 2.7.7 }
          - { name: "3.0", value: 3.0.5 }
          - { name: "3.1", value: 3.1.3 }

        include:
          - ruby: { name: jruby-9.3, value: jruby-9.3.9.0 }
            os: { name: Ubuntu, value: ubuntu-22.04 }

          - ruby: { name: truffleruby-22, value: truffleruby-22.3.0 }
            os: { name: Ubuntu, value: ubuntu-22.04 }

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Setup ruby
        uses: ruby/setup-ruby@09c10210cc6e998d842ce8433cd9d245933cd797 # v1.133.0
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Test
        run: rake test
        if: "!startsWith(matrix.ruby.name, 'truffleruby') && !startsWith(matrix.ruby.name, 'jruby')"
      - name: Run Test isolatedly
        run: rake test:isolated
        if: matrix.ruby.name == '3.1'
      - name: Run Test (JRuby)
        run: JRUBY_OPTS=--debug rake test
        if: startsWith(matrix.ruby.name, 'jruby')
      - name: Run Test (Truffleruby)
        run: TRUFFLERUBYOPT="--experimental-options --testing-rubygems" rake test
        if: startsWith(matrix.ruby.name, 'truffleruby')

    timeout-minutes: 60
