name: ruby-core

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ruby_core:
    name: ${{matrix.target}} under a ruby-core setup
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target: [Rubygems, Bundler]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ruby/ruby
          path: ruby/ruby
          ref: 2cce628721728409a26c2d4732f63419785c7fd8 # TODO: Point to v3_4_5 once released
          persist-credentials: false
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update -q || :
          sudo apt-get install --no-install-recommends -q -y build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm-dev bison autoconf ruby
      - name: Build Ruby
        run: |
          ./autogen.sh
          ./configure -C --disable-install-doc
          make -j2
        working-directory: ruby/ruby
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: rubygems/rubygems
          persist-credentials: false
      - name: Sync tools
        run: |
          ruby tool/sync_default_gems.rb rubygems
          mv spec/bundler/support/bundle spec/bin/bundle # TODO: fix `sync_default_gems.rb` script so we don't need to vendor the ruby-core binstub ourselves
        working-directory: ruby/ruby
      - name: Test RubyGems
        run: make -j2 -s test-all TESTS="rubygems --no-retry"
        working-directory: ruby/ruby
        if: matrix.target == 'Rubygems'
      - name: Test Bundler
        run: |
          git add .
          make test-bundler-parallel
        working-directory: ruby/ruby
        if: matrix.target == 'Bundler'

  all-pass:
    name: All ruby-core jobs pass

    if: always()

    needs:
      - ruby_core

    runs-on: ubuntu-latest

    steps:
      - name: check dependent jobs
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
