name: rubygems

on:
  pull_request:
  merge_group:

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  rubygems:
    name: Rubygems on ${{ matrix.os.name }} (${{ matrix.ruby.name }})
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: Ubuntu, value: ubuntu-22.04 }
          - { name: macOS, value: macos-12 }
          - { name: Windows, value: windows-2022 }

        ruby:
          - { name: "2.6", value: 2.6.10 }
          - { name: "2.7", value: 2.7.7 }
          - { name: "3.0", value: 3.0.5 }
          - { name: "3.1", value: 3.1.3 }
          - { name: "3.2", value: 3.2.1 }

        include:
          - ruby: { name: "3.2", value: 3.2.1 }
            os: { name: macOS, value: macos-12 }

          - ruby: { name: jruby-9.4, value: jruby-9.4.2.0 }
            os: { name: Ubuntu, value: ubuntu-22.04 }

          - ruby: { name: truffleruby-22, value: truffleruby-22.3.0 }
            os: { name: Ubuntu, value: ubuntu-22.04 }

          - os: { name: Windows, value: windows-2022 }
            ruby: { name: mswin, value: mswin }

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Setup ruby (Ubuntu/macOS)
        uses: ruby/setup-ruby@904f3fef85a9c80a3750cbe7d5159268fd5caa9f # v1.145.0
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
        if: matrix.os.name != 'Windows'
      - name: Setup ruby (Windows)
        uses: ruby/setup-ruby-pkgs@af45875e8df3485265907b05fe263a4a1a07eeb2 # v1.32.4
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
          mingw: clang
        if: matrix.os.name == 'Windows'
      - name: Configure bindgen
        shell: pwsh
        run: |
          echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
          echo "BINDGEN_EXTRA_CLANG_ARGS=$((gcm clang).source -replace "bin\clang.exe","include")" >> $env:GITHUB_ENV
        if: matrix.ruby.name == 'mswin'
      - name: Install Dependencies
        run: rake setup
      - name: Run Test
        run: rake test
        if: "!startsWith(matrix.ruby.name, 'truffleruby') && !startsWith(matrix.ruby.name, 'jruby')"
      - name: Run Test isolatedly
        run: rake test:isolated
        if: matrix.ruby.name == '3.2' && matrix.os.name != 'Windows'
      - name: Run Test (JRuby)
        run: JRUBY_OPTS=--debug rake test
        if: startsWith(matrix.ruby.name, 'jruby')
      - name: Run Test (Truffleruby)
        run: TRUFFLERUBYOPT="--experimental-options --testing-rubygems" rake test
        if: startsWith(matrix.ruby.name, 'truffleruby')

    timeout-minutes: 60
