name: ğŸ’ Spellchecker

on: [pull_request]

jobs:
  misspell:
    name: ğŸ§¹ Check Spelling
    runs-on: ubuntu-20.04
    steps:
      - name: ğŸ“ Check Out
        uses: actions/checkout@v2
      - name: ğŸ Install
        run: |
          wget -O - -q https://git.io/misspell | sh -s -- -b .
      - name: ğŸŒ¶ï¸ Misspell
        run: |
          find . -type f -not -path "./bundler/spec/support/artifice/vcr_cassettes/realworld/index.rubygems.org/versions**" | xargs ./misspell -i "automatiek,wille"
