name: ubuntu-lint

on:
  pull_request:
  merge_group:

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ubuntu_lint:
    name: Lint
    runs-on: ubuntu-22.04
    env:
      RUBYOPT: -Ilib
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Setup ruby
        uses: ruby/setup-ruby@8a45918450651f5e4784b6031db26f4b9f76b251 # v1.150.0
        with:
          ruby-version: 3.2.1
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Lint
        run: rake rubocop
      - name: Generate docs
        run: rake docs
      - name: Install & Check Dependencies
        run: bin/rake dev:frozen_deps
      - name: Misc checks
        run: bin/rake check_rvm_integration man:check check_rubygems_integration
    timeout-minutes: 15
