name: ubuntu-bundler3

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  ubuntu_bundler3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.4.9, 2.5.7, 2.6.5 ]
        rgv: [ v3.0.6, .. ]
    env:
      RGV: ${{ matrix.rgv }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Prepare dependencies
        run: |
          BUNDLER_SPEC_SUB_VERSION=3.0.0 bin/rake override_version
          bin/rake spec:parallel_deps
        working-directory: ./bundler
      - name: Run Test
        run: |
          bin/parallel_rspec spec
        working-directory: ./bundler
      - name: Run Test with realworld
        run: |
          bin/rake spec:realworld
        env:
          BUNDLER_SPEC_PRE_RECORDED: 1
        working-directory: ./bundler
      - name: Run Test with sudo
        run: |
          bin/rake spec:sudo
        working-directory: ./bundler
    timeout-minutes: 60
