name: ubuntu-lint

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ubuntu_lint:
    name: Lint
    runs-on: ubuntu-22.04
    env:
      RUBYOPT: -Ilib
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Setup ruby
        uses: ruby/setup-ruby@6bd3d993c602f6b675728ebaecb2b569ff86e99b # v1.174.0
        with:
          ruby-version: 3.3.0
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Lint
        run: rake rubocop
      - name: Generate docs
        run: rake docs
      - name: Install & Check Dependencies
        run: bin/rake dev:frozen_deps
      - name: Misc checks
        run: bin/rake check_rvm_integration man:check vendor:check version:check check_rubygems_integration
    timeout-minutes: 15
