name: ubuntu-lint

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  python_linters:
    name: Python linter ${{ matrix.command }}
    runs-on: ubuntu-24.04
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        command:
          - codespell
          - yamllint
          - zizmor
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"
      - name: Install Dependencies
        run: pip install -r .github/workflows/lint.requirements.txt

      - name: Run codespell
        run: codespell
        if: matrix.command == 'codespell'
      - name: Run YAMLlint
        run: yamllint .
        if: matrix.command == 'yamllint'
      - name: Run zizmor ðŸŒˆ
        run: zizmor --format=sarif . > results.sarif
        if: matrix.command == 'zizmor'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@60168efe1c415ce0f5521ea06d5c2062adbeed1b # v3.28.17
        if: matrix.command == 'zizmor'
        with:
          sarif_file: results.sarif
          category: zizmor

  ruby_linters:
    name: Ruby linters on ${{ matrix.ruby.name }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: ruby, value: 3.4.4 }
          - { name: jruby, value: jruby-10.0.0.1 }
          - { name: truffleruby, value: truffleruby-24.2.0 }
    env:
      RUBYOPT: -Ilib
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Setup ruby
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1.245.0
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install Dependencies
        run: bin/rake setup
      - name: Run Ruby Lint
        run: bin/rake rubocop
      - name: Run Markdown Lint
        run: bin/mdl -g . -r MD001,MD025
        if: matrix.ruby.name == 'ruby'
      - name: Generate docs
        run: bin/rake docs
        if: matrix.ruby.name != 'jruby'
      - name: Install & Check Dependencies
        run: bin/rake dev:frozen_deps
      - name: Misc checks
        run: bin/rake check_rvm_integration man:check vendor:check version:check check_rubygems_integration
        if: matrix.ruby.name != 'jruby'
    timeout-minutes: 15

  all-pass:
    name: All ubuntu-lint jobs pass

    if: always()

    needs:
      - python_linters
      - ruby_linters
    runs-on: ubuntu-latest

    steps:
      - name: check dependent jobs
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
