name: ubuntu-rubygems

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2

jobs:
  ubuntu_rubygems:
    name: Rubygems on Ubuntu (${{ matrix.ruby.name }})
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: "2.3", value: 2.3.8 }
          - { name: "2.4", value: 2.4.10 }
          - { name: "2.5", value: 2.5.9 }
          - { name: "2.6", value: 2.6.7 }
          - { name: "2.7", value: 2.7.3 }
          - { name: "3.0", value: 3.0.1 }
          - { name: jruby-9.2, value: jruby-9.2.16.0 }
          - { name: truffleruby-20.3, value: truffleruby-20.3.0 }
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Test
        run: rake test
        if: "!startsWith(matrix.ruby.name, 'truffleruby') && !startsWith(matrix.ruby.name, 'jruby')"
      - name: Run Test (JRuby)
        run: JRUBY_OPTS=--debug rake test
        if: startsWith(matrix.ruby.name, 'jruby')
      - name: Run Test (Truffleruby)
        run: TRUFFLERUBYOPT="--experimental-options --testing-rubygems" rake test
        if: startsWith(matrix.ruby.name, 'truffleruby')

    timeout-minutes: 60
