name: ubuntu-bundler

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  ubuntu_bundler:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.3.8, 2.4.9, 2.5.7, 2.6.5, 2.7.0 ]
        rgv: [ v2.5.2, v2.6.14, v2.7.10, v3.0.6, v3.1.2, .. ]
        exclude:
          - ruby: 2.4.9
            rgv: v2.5.2
          - ruby: 2.5.7
            rgv: v2.5.2
          - ruby: 2.5.7
            rgv: v2.6.14
          - ruby: 2.6.5
            rgv: v2.5.2
          - ruby: 2.6.5
            rgv: v2.6.14
          - ruby: 2.6.5
            rgv: v2.7.10
          - ruby: 2.7.0
            rgv: v2.5.2
          - ruby: 2.7.0
            rgv: v2.6.14
          - ruby: 2.7.0
            rgv: v2.7.10
          - ruby: 2.7.0
            rgv: v3.0.6
    env:
      RGV: ${{ matrix.rgv }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Prepare dependencies
        run: |
          sudo apt-get install graphviz -y
          bin/rake spec:parallel_deps
        working-directory: ./bundler
      - name: Run Test
        run: |
          bin/rake spec:all
        working-directory: ./bundler
    timeout-minutes: 60
