name: ubuntu-lint

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ubuntu_lint:
    name: Lint on ${{ matrix.ruby.name }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: ruby, value: 3.4.2 }
          - { name: jruby, value: jruby-9.4.12.0 }
          - { name: truffleruby, value: truffleruby-24.1.2 }
    env:
      RUBYOPT: -Ilib
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup ruby
        uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252 # v1.229.0
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install Dependencies
        run: bin/rake setup
      - name: Run Lint
        run: bin/rake rubocop
      - name: Generate docs
        run: bin/rake docs
        if: matrix.ruby.name != 'jruby'
      - name: Install & Check Dependencies
        run: bin/rake dev:frozen_deps
      - name: Misc checks
        run: bin/rake check_rvm_integration man:check vendor:check version:check check_rubygems_integration
        if: matrix.ruby.name != 'jruby'
    timeout-minutes: 15
