name: ubuntu-lint

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ubuntu_lint:
    name: Lint on ${{ matrix.ruby.name }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: ruby, value: 3.3.5 }
          - { name: truffleruby, value: truffleruby-24.0.1 }
    env:
      RUBYOPT: -Ilib
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup ruby
        uses: ruby/setup-ruby@a6b46b8a08edb18935835849f2a17072d5cc8c73 # v1.192.0
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install Dependencies
        run: bin/rake setup
      - name: Run Lint
        run: bin/rake rubocop
      - name: Generate docs
        run: bin/rake docs
      - name: Install & Check Dependencies
        run: bin/rake dev:frozen_deps
      - name: Misc checks
        run: bin/rake check_rvm_integration man:check vendor:check version:check check_rubygems_integration
    timeout-minutes: 15
