name: ubuntu-lint

on:
  pull_request:
  merge_group:

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ubuntu_lint:
    name: Lint
    runs-on: ubuntu-22.04
    env:
      RUBYOPT: -Ilib
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup ruby
        uses: ruby/setup-ruby@d3c9825d67b0d8720afdfdde5af56c79fdb38d16 # v1.138.0
        with:
          ruby-version: 3.2.1
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Lint
        run: rake rubocop
      - name: Generate docs
        run: rake docs
      - name: Install & Check Dependencies
        run: bin/rake dev:frozen_deps
        working-directory: ./bundler
      - name: Misc checks
        run: bin/rake check_rvm_integration man:check check_rubygems_integration
        working-directory: ./bundler
    timeout-minutes: 15
