name: ubuntu-lint

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2

jobs:
  ubuntu_lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Lint
        run: rake rubocop
      - name: Generate docs
        run: rake docs
      - name: Install & Check Dependencies
        run: bin/rake dev:frozen_deps
        working-directory: ./bundler
      - name: "Check RVM integration, man:check"
        run: bin/rake check_rvm_integration man:check
        working-directory: ./bundler
    timeout-minutes: 15
