name: ubuntu-bundler-master

on:
  pull_request:

  push:
    branches:
      - staging
      - trying

jobs:
  ubuntu_bundler_master:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6.x' ]
    steps:
      - uses: actions/checkout@v1
      - run: git submodule update -i
      - name: Fixed world writable dirs
        run: |
          chmod go-w $HOME
          sudo chmod -R go-w /usr/share
          sudo chmod -R go-w /opt
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Dependencies
        run: util/ci.sh before_script
        env:
          TEST_TOOL: "bundler"
          BDV: "master"
      - name: Run Test
        run: util/ci.sh script
        env:
          TEST_TOOL: "bundler"
    timeout-minutes: 60
