name: ubuntu-lint

on:
  pull_request:

  push:
    branches:
      - master
      - 3.4

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  ubuntu_lint:
    name: Lint
    runs-on: ubuntu-22.04
    env:
      RUBYOPT: -Ilib
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - name: Setup ruby
        uses: ruby/setup-ruby@e6689b4deb1cb2062ea45315001f687c0b52111b # v1.144.1
        with:
          ruby-version: 3.2.1
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Lint
        run: rake rubocop
      - name: Generate docs
        run: rake docs
      - name: Install & Check Dependencies
        run: bin/rake dev:frozen_deps
        working-directory: ./bundler
      - name: Misc checks
        run: bin/rake check_rvm_integration man:check check_rubygems_integration
        working-directory: ./bundler
    timeout-minutes: 15
