name: ubuntu

on:
  pull_request:
    paths-ignore:
      - "bundler/**"
      - ".github/workflows/*bundler*.yml"

  push:
    branches:
      - master
      - "pr-**"
    paths-ignore:
      - "bundler/**"
      - ".github/workflows/*bundler*.yml"

jobs:
  ubuntu:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby: [ 2.3.8, 2.4.10, 2.5.8, 2.6.6, 2.7.1, jruby-9.2.11.1, truffleruby-head ]
    env:
      TRUFFLERUBYOPT: "--experimental-options --testing-rubygems"
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Install Dependencies
        run: rake setup
      - name: Run Test
        run: rake test
    timeout-minutes: 60
