name: ubuntu-rubygems

on:
  pull_request:

  push:
    branches:
      - standalone_require
      - master
      - 3.3

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  ubuntu_rubygems:
    name: Rubygems on Ubuntu (${{ matrix.ruby.name }})
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: "2.3", value: 2.3.8 }
          - { name: "2.4", value: 2.4.10 }
          - { name: "2.5", value: 2.5.9 }
          - { name: "2.6", value: 2.6.10 }
          - { name: "2.7", value: 2.7.6 }
          - { name: "3.0", value: 3.0.4 }
          - { name: "3.1", value: 3.1.2 }
          - { name: jruby-9.3, value: jruby-9.3.4.0 }
          - { name: truffleruby-21, value: truffleruby-21.3.0 }
    steps:
      - uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Dependencies
        run: rake setup
      - name: Run Test
        run: rake test
        if: "!startsWith(matrix.ruby.name, 'truffleruby') && !startsWith(matrix.ruby.name, 'jruby')"
      - name: Run Test isolatedly
        run: rake test:isolated
        if: matrix.ruby.name == '3.1'
      - name: Run Test (JRuby)
        run: JRUBY_OPTS=--debug rake test
        if: startsWith(matrix.ruby.name, 'jruby')
      - name: Run Test (Truffleruby)
        run: TRUFFLERUBYOPT="--experimental-options --testing-rubygems" rake test
        if: startsWith(matrix.ruby.name, 'truffleruby')

    timeout-minutes: 60
