name: windows-rubygems

on:
  pull_request:

  push:
    branches:
      - master
      - 3.3

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  windows_rubygems:
    name: Rubygems on Windows (${{ matrix.ruby.name }})
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        cargo:
          - target: x86_64-pc-windows-gnu
            toolchain: stable
        ruby:
          - { name: "2.4", value: 2.4.10 }
          - { name: "2.5", value: 2.5.9 }
          - { name: "2.6", value: 2.6.9 }
          - { name: "2.7", value: 2.7.5 }
          - { name: "3.0", value: 3.0.3 }
          - { name: "3.1", value: 3.1.0 }
          - { name: mswin, value: mswin }
    steps:
      - uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.cargo.toolchain }}-${{ matrix.cargo.target }}
          default: true
      - name: Fix clang dep for rust-bindgen (see https://github.com/rubygems/rubygems/pull/5175#discussion_r794873977) 
        if: ${{ matrix.ruby.name != 'mswin' }}
        run: |
          pacman --remove --cascade mingw-w64-x86_64-clang
          pacman --sync --noconfirm --needed $ENV:MINGW_PACKAGE_PREFIX-clang
      - name: Print debugging info
        run: |
          echo "RbConfig::MAKEFILE_CONFIG"
          echo "========================="
          ruby -rrbconfig -ryaml -e 'puts YAML.dump(RbConfig::MAKEFILE_CONFIG)'
          echo "========================="

          echo "Machine info"
          echo "========================="
          uname -a
          echo "========================="
      - name: Install Dependencies and Run Test
        run: |
          rake setup
          rake test
        env:
          BUNDLE_WITHOUT: lint
    timeout-minutes: 15
