name: windows

on: [push]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [ '2.4.x', '2.5.x', '2.6.x' ]
    steps:
      - uses: actions/checkout@master
      - run: git submodule update -i
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Dependencies
        run: TEST_TOOL=rubygems util/ci.sh before_script
        shell: bash
      - name: Run Test
        # create a symlink for git to a folder without a space, needed for CI only
        run: |
          New-Item -Path "C:\git" -ItemType Junction -Value "C:\Program Files\Git" 1> $null
          $env:GIT = "C:\git\cmd\git.exe"
          ridk enable
          rake test
    timeout-minutes: 15
