name: windows-rubygems

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  windows_rubygems:
    name: Rubygems on Windows (${{ matrix.ruby.name }})
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: "2.4", value: 2.4.10 }
          - { name: "2.5", value: 2.5.9 }
          - { name: "2.6", value: 2.6.9 }
          - { name: "2.7", value: 2.7.7 }
          - { name: "3.0", value: 3.0.5 }
          - { name: "3.1", value: 3.1.3 }
          # - { name: mswin, value: mswin }
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install Dependencies and Run Test
        run: |
          rake setup
          rake test
        env:
          BUNDLE_WITHOUT: lint
    timeout-minutes: 15
