name: windows-rubygems

on:
  pull_request:

  push:
    branches:
      - master
      - 3.4

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  windows_rubygems:
    name: Rubygems on Windows (${{ matrix.ruby.name }})
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        cargo:
          - target: x86_64-pc-windows-gnu # mingw
            toolchain: stable
        ruby:
          - { name: "2.6", value: 2.6.10 }
          - { name: "2.7", value: 2.7.7 }
          - { name: "3.0", value: 3.0.5 }
          - { name: "3.1", value: 3.1.3 }
        include:
          - ruby: { name: "mswin", value: "mswin" }
            cargo: { target: x86_64-pc-windows-msvc, toolchain: stable } # mswin
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Setup ruby
        uses: ruby/setup-ruby-pkgs@e5897b3f277d700f7b9e24b5819112945add74ff # v1.32.3
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
          mingw: clang
      - uses: dtolnay/rust-toolchain@e645b0cf01249a964ec099494d38d2da0f0b349f
        with:
          toolchain: ${{ matrix.cargo.toolchain }}-${{ matrix.cargo.target }}
          components: rustfmt
      - name: Print debugging info
        run: |
          echo "RbConfig::MAKEFILE_CONFIG"
          echo "========================="
          ruby -rrbconfig -ryaml -e 'puts YAML.dump(RbConfig::MAKEFILE_CONFIG)'
          echo "========================="

          echo "Machine info"
          echo "========================="
          uname -a
          echo "========================="
      # Taken from https://github.com/oxidize-rb/actions/blob/0d21ce09c5500315bc61815440f8c4211530f413/setup-ruby-and-rust/action.yml#LL300-L305C116
      - name: Configure bindgen
        if: contains(matrix.cargo.target, 'msvc')
        shell: pwsh
        run: |
          echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
          echo "BINDGEN_EXTRA_CLANG_ARGS=$((gcm clang).source -replace "bin\clang.exe","include")" >> $env:GITHUB_ENV
      - name: Install Dependencies and Run Test
        run: |
          rake setup
          rake test
        env:
          BUNDLE_WITHOUT: lint
    timeout-minutes: 25
