name: windows-bundler

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  windows_bundler:
    name: Bundler on Windows (${{ matrix.ruby.name }})

    runs-on: windows-2019

    env:
      RGV: ..

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: jruby-9.3, value: jruby-9.3.1.0 }
          - { name: ruby-2.5, value: 2.5.9 }
          - { name: ruby-3.0, value: 3.0.5 }
          # - { name: ruby-3.1, value: 3.1.3 }

    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
        if: startsWith(matrix.ruby.name, 'jruby')
      - name: Install dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: |
          bin/parallel_rspec
        working-directory: ./bundler
        shell: bash
        if: "!startsWith(matrix.ruby.name, 'jruby')"
